"""D1: per-token estimator recompute on the frozen round-8 E1 weights.

Pre-lock development phase of notes/prereg-gating-corrected-rho.md.
Development-set by construction (E1's summary statistics informed the
round-9 estimator design). Measures, token-by-token on the 48 absorbed
E1 runs (m in {128, 256}, true rho = 0.5, eps = 0.002):

  - all four estimators at the O (all tokens) and M (oracle J-union-S)
    endpoints,
  - delta_J, delta_S (tokenwise dominance-inversion rates: the F4 test),
  - background pattern cells q_ij, pi_B, h_B, tie rates,
  - decoder-norm (S1) check.

Eval stream regenerates E1's own labeled eval protocol (generator 9000+s,
200k draws) against the committed weights; needs activations_l6.pt
(regenerated by experiments/extract_activations.py if absent).

Output: results/round9/d1_e1_recompute.csv + printed per-width summary.
The F4 verdict here gates the prereg lock (see prereg pre-lock phase).
"""
import torch, math, csv, os, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "..", "experiments"))
from rho_estimators_lib import (rho_estimators, theta_sensitivity,
                                oracle_diags)

dev = "cuda" if torch.cuda.is_available() else "cpu"

def safe_load(path):
    """weights_only=True where supported; the orchestrator's torch 1.13
    either lacks the kwarg or its restricted unpickler cannot read
    torch-2.5-saved files (UnpicklingError) - fall back to a full load,
    which is acceptable only because these files are project-generated."""
    import pickle
    try:
        return torch.load(path, weights_only=True)
    except (TypeError, pickle.UnpicklingError):
        return torch.load(path)

D_MODEL, AMP, Q, P0 = 768, 5.0, 0.2, 0.2
N_EV = 200_000
R8DIR = os.path.join(HERE, "..", "results", "round8")
OUTDIR = os.path.join(HERE, "..", "results", "round9")
os.makedirs(OUTDIR, exist_ok=True)

ACT = os.path.join(HERE, "..", "experiments", "activations_l6.pt")
if not os.path.exists(ACT):
    try:
        import transformers  # noqa
    except ImportError:
        import subprocess
        subprocess.run([sys.executable, "-m", "pip", "install", "--user",
                        "-q", "transformers"], check=True)
    os.chdir(os.path.join(HERE, "..", "experiments"))  # extractor writes to CWD
    import extract_activations
    extract_activations.main()
bg = safe_load(ACT).float()
mu = bg.mean(0, keepdim=True)
bg = ((bg - mu) * math.sqrt(D_MODEL) / (bg - mu).norm(dim=1).mean()).half().to(dev)
N = bg.shape[0]

rows_csv = []
for M_LAT in (128, 256):
    wpath = os.path.join(R8DIR, f"weights_r8e1_m{M_LAT}.pt")
    blob = safe_load(wpath)
    W_all, b_all, D_all, runs = blob["W"], blob["b"], blob["D"], blob["runs"]
    for i, (e, s) in enumerate(runs):
        if abs(float(e) - 0.002) > 1e-9:
            continue                      # absorbed-regime rows only
        g = torch.Generator().manual_seed(300 + s)
        Qm, _ = torch.linalg.qr(torch.randn(D_MODEL, 2, generator=g))
        ap_, ac_ = Qm.T[0].to(dev), Qm.T[1].to(dev)
        comp_dir = (ap_ + ac_) / math.sqrt(2)
        Di = D_all[i].to(dev)
        Wi = W_all[i].to(dev); bi = b_all[i].to(dev)
        par = int(torch.einsum('dm,d->m', Di, ap_).abs().argmax())
        comp = int(torch.einsum('dm,d->m', Di, comp_dir).abs().argmax())
        cos_comp = float(torch.einsum('dm,d->m', Di, comp_dir).abs().max())
        row = dict(m=M_LAT, seed=s, absorbed=int(cos_comp > 0.98 and par != comp),
                   cos_comp=round(cos_comp, 4),
                   dnorm_par=round(float(Di[:, par].norm()), 5),
                   dnorm_comp=round(float(Di[:, comp].norm()), 5))
        if not row["absorbed"]:
            rows_csv.append(row); continue
        g2 = torch.Generator(device=dev).manual_seed(9000 + s)
        apar, acomp, labels = [], [], []
        for c0 in range(0, N_EV, 50_000):
            n = min(50_000, N_EV - c0)
            idx = torch.randint(0, N, (n,), device=dev, generator=g2)
            x = bg[idx].float()
            u = torch.rand(n, device=dev, generator=g2)
            jj = (u < Q).float(); pp = ((u >= Q) & (u < Q + P0)).float()
            cc = ((u >= Q + P0) & (u < Q + P0 + e)).float()
            x = (x + AMP * (jj + pp).unsqueeze(-1) * ap_
                   + AMP * (jj + cc).unsqueeze(-1) * ac_)
            f = torch.relu(x @ Wi.T + bi)
            apar.append(f[:, par].cpu().numpy())
            acomp.append(f[:, comp].cpu().numpy())
            labels.append(torch.stack([jj, pp]).cpu().numpy())
        ap_np = np.concatenate(apar); ac_np = np.concatenate(acomp)
        jj, pp = np.concatenate(labels, axis=1)
        mJ = jj > 0.5; mS = pp > 0.5; mB = ~(mJ | mS)
        row.update(rho_estimators(ap_np, ac_np))
        mJS = mJ | mS
        row.update({f"m_{k}": v for k, v in
                    rho_estimators(ap_np[mJS], ac_np[mJS]).items()})
        row.update(theta_sensitivity(ap_np, ac_np))
        row.update(oracle_diags(ap_np, ac_np, mJ, mS, mB))
        rows_csv.append(row)
        print(f"[m={M_LAT} s{s}] rho_d={row['rho_d']} m_rho_d={row['m_rho_d']} "
              f"dJ={row['delta_J']} dS={row['delta_S']} hB={row['h_B']} "
              f"ties={row['ties']}", flush=True)

fields = []
for r in rows_csv:
    for k in r:
        if k not in fields: fields.append(k)
out = os.path.join(OUTDIR, "d1_e1_recompute.csv")
with open(out, "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=fields)
    w.writeheader(); w.writerows(rows_csv)
print(f"wrote {out} ({len(rows_csv)} rows)")

# ------------------------------------------------------------ summary
import statistics as st
absorbed = [r for r in rows_csv if r.get("absorbed")]
for M_LAT in (128, 256):
    sub = [r for r in absorbed if r["m"] == M_LAT]
    if not sub: continue
    def col(c):
        v = [float(r[c]) for r in sub if not (isinstance(r[c], float) and math.isnan(r[c]))]
        return (st.mean(v), st.stdev(v) if len(v) > 1 else 0.0)
    print(f"\n== m={M_LAT} (n={len(sub)}, true rho=0.5) ==")
    for c in ("rho_count", "rho_c", "rho_x", "rho_d", "m_rho_d",
              "delta_J", "delta_S", "pi_B", "h_B", "q11_B", "b_p", "b_c",
              "ties", "rho_real"):
        mn, sd = col(c)
        print(f"  {c}: {mn:.4f} +/- {sd:.4f}")
